UPSTREAM: can: mcp25xxfd: mcp25xxfd_irq(): add missing initialization of variable set_normal mode
commit 727fba74b511 ("can: mcp25xxfd: mcp25xxfd_irq(): add missing
initialization of variable set_normal mode") upstream.

This patch fixes the following warning:

    drivers/net/can/spi/mcp25xxfd/mcp25xxfd-core.c:2155 mcp25xxfd_irq()
    error: uninitialized symbol 'set_normal_mode'.

by adding the missing initialization.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Reviewed-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
Fixes: 55e5b97f003e ("can: mcp25xxfd: add driver for Microchip MCP25xxFD SPI CAN")
Link: https://lore.kernel.org/r/20200923114726.2704426-1-mkl@pengutronix.de
Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>
Signed-off-by: Dominik Haller <d.haller@phytec.de>
Signed-off-by: Teresa Remmet <t.remmet@phytec.de>